spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/students/**
          - id: colleges
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/colleges/**


server:
  port: 9898

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
      group:
        my-health-group:
          include: ping, diskSpace
  endpoints:
    web:
      #      base-path: /actuator
      #      path-mapping:
      #        health: healthcheck
      exposure:
        include: "*"

