spring:
  application:
    name: students
  jpa:
    generate-ddl: 'true'
    database: default
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
      max_allowed_packet: '2000'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_students?createDatabaseIfNotExist=true
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ToDoHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

management:
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
      group:
        my-health-group:
          include: ping, diskSpace
  endpoints:
    web:
      #      base-path: /actuator
      #      path-mapping:
      #        health: healthcheck
      exposure:
        include: "*"
